# Generated by Django 4.2.13 on 2024-07-08 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipe_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["created_on"]},
        ),
    ]
