# Generated by Django 4.2.13 on 2024-07-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
