# Generated by Django 5.0.6 on 2024-07-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0002_about_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={},
        ),
        migrations.RenameField(
            model_name="about",
            old_name="updated_at",
            new_name="updated_on",
        ),
        migrations.RemoveField(
            model_name="about",
            name="created_on",
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
